apiVersion: v1
kind: Namespace
metadata:
  name: graylog
  labels:
    name: graylog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: graylog
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3    
          ports:
            - containerPort: 27017        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: graylog
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
          resources:
            limits:
              memory: "1024Mi"
            requests:
              memory: "1024Mi"
          env:
            - name: http.host
              value: 0.0.0.0
            - name: transport.host
              value: localhost
            - name: network.host
              value: 0.0.0.0
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:3.2
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: somepasswordpepper
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://127.0.0.1:30000/
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 1514
              protocol: TCP
            - containerPort: 1514
              protocol: UDP
            - containerPort: 12201
              protocol: TCP
            - containerPort: 12201
              protocol: UDP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: graylog
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.6-management
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
            - name: RABBITMQ_DEFAULT_USER
              value: admin
          ports:
            - containerPort: 15672
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: graylog  
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector: 
    app: mongo  
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: graylog  
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector: 
    app: elasticsearch  
  ports:
    - port: 9200
      targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: graylog-service
  namespace: graylog  
  labels:
    app: graylog
spec:
  type: NodePort
  selector: 
    app: graylog  
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
      name: "port1"
    - port: 1514
      targetPort: 1514
      nodePort: 30001
      name: "port2"
    - port: 12201
      targetPort: 12201
      nodePort: 30002
      name: "port3"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: graylog  
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector: 
    app: rabbitmq  
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 31567
      name: "port1"
    - port: 5672
      targetPort: 5672
      nodePort: 30567
      name: "port2"