version: '3'

networks:
  default-network:
    driver: bridge

services:
  mongo:
    image: mongo:3
    networks:
      - default-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - default-network
  graylog:
    image: graylog/graylog:3.2
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9009/
    networks:
      - default-network
    depends_on:
      - mongo
      - elasticsearch
      - rabbitmq
    ports:
      - 9009:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
      
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    environment:
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_USER=admin
    tty: true
    image: rabbitmq:3.6-management
    stdin_open: true
    networks:
      - default-network
      
      